repository:
  name: M2SH Home Assistant Add-ons
  description: A collection of Home Assistant add-ons by Mohammad Shahgolzadeh
  url: https://github.com/m2sh/ha-addons
  maintainer: Mohammad Shahgolzadeh <https://github.com/m2sh/>
  version: 1.0.0
addons:
  chisel:
    repo: https://github.com/m2sh/ha-addon-chisel
    branch: main
    version: 0.0.5
