---
name: "Chisel"
version: "1.9.1"
slug: "chisel"
description: "A fast TCP/UDP tunnel over HTTP, secured via SSH"
repository: https://github.com/m2sh/ha-addon-chisel
url: "https://github.com/m2sh/ha-addon-chisel/"
codenotary: dev@example.com
init: false
hassio_api: true
hassio_role: homeassistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: "ghcr.io/m2sh/ha-addon-chisel/{arch}"
map:
  - config:rw
  - ssl:rw
options:
  mode: "server"
  # Server options
  server_port: 8080
  server_keyfile: ""
  server_authfile: ""
  server_socks5: false
  server_reverse: false
  server_proxy: ""
  server_header: []
  # Client options
  client_server: ""
  client_fingerprint: ""
  client_auth: ""
  client_remotes: []
  client_keepalive: "25s"
  client_max_retry_count: 0
  client_max_retry_interval: "5m"
  client_proxy: ""
  client_header: []
  client_hostname: ""
  client_sni: ""
  client_tls_ca: ""
  client_tls_skip_verify: false
  client_tls_key: ""
  client_tls_cert: ""
  # Common options
  log_level: info
  pid: false
  verbose: false
ports:
  8080/tcp: 8080
  8081/tcp: 8081
  8082/tcp: 8082
  8083/tcp: 8083
  8084/tcp: 8084
  8085/tcp: 8085
  8086/tcp: 8086
  8087/tcp: 8087
  8088/tcp: 8088
  8089/tcp: 8089
  8090/tcp: 8090
schema:
  mode: list(server|client)
  # Server options
  server_port: port
  server_keyfile: str?
  server_authfile: str?
  server_socks5: bool?
  server_reverse: bool?
  server_proxy: str?
  server_header:
    - str
  # Client options
  client_server: str?
  client_fingerprint: str?
  client_auth: str?
  client_remotes:
    - str
  client_keepalive: str?
  client_max_retry_count: int?
  client_max_retry_interval: str?
  client_proxy: str?
  client_header:
    - str
  client_hostname: str?
  client_sni: str?
  client_tls_ca: str?
  client_tls_skip_verify: bool?
  client_tls_key: str?
  client_tls_cert: str?
  # Common options
  log_level: list(trace|debug|info|warning|error|fatal)
  pid: bool?
  verbose: bool?
webui: "http://[HOST]:[PORT:8080]"
ingress: true
ingress_port: 8080
panel_icon: mdi:tunnel
homeassistant_api: false
