name: Update Add-ons

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'addons.yml'

jobs:
  update-addons:
    runs-on: ubuntu-latest
    name: Update add-ons from repositories
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Update add-ons
        run: |
          python scripts/update_addons.py
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git add -A
          git commit -m "🔄 Update add-ons from repositories [skip ci]

          Auto-updated add-ons:
          $(git diff --name-only HEAD~1 HEAD | grep -E '^[^/]+/$' | head -10 | sed 's/^/- /' || echo '- Various files updated')"
      
      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 